name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, primary]
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
        with:
          clean: false

      - name: Check versions
        shell: bash -l {0}
        run: |
          source $HOME/.bashrc
          node --version
          npm --version

      - name: Install dependencies
        run: yarn install

      - name: Inject environment variables
        run: |
          touch .env
          echo BOT_TOKEN=${{ secrets.BOT_TOKEN }} > .env

      - name: Restart PM2
        run: pm2 restart clone-bot
