name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, primary]
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
        with:
          clean: false

      - name: Build Docker
        uses: docker/build-push-action@v2.7.0
        with:
          tags: clone-bot
          push: false
          build-args: |
            bot_token=${{ secrets.BOT_TOKEN }}

      - name: Run Docker
        run: docker run clone-bot
